apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: aGFycnk=
  password: cGFzc3dvcmQ=
  database: bm90aWZpY2F0aW9ucw==
  host: bW9uZ28tZGF0YWJhc2U=
  port: MjcwMTc=
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo
spec:
  containers:
  - name: mongo-container
    image: mongo:latest
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: username
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: password
    - name: MONGO_INITDB_DATABASE
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: database
    volumeMounts:
    - name: mongo-data
      mountPath: /bitnami/mongo
  volumes:
  - name: mongo-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
