apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-external-secret-redis
spec:
  refreshInterval: 600s
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: redis-secret # secret name to be created in k8s
    creationPolicy: Owner
  data:
  - secretKey: addr # key in the k8s secret
    remoteRef:
      key: redis-credentials # secret name used in the external secret store
      property: addr # key name used in the external secret store
  - secretKey: password # key in the k8s secret
    remoteRef: 
      key: redis-credentials # secret name used in the external secret store
      property: password # key name used in the external secret store
