apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-external-secret-postgresdb
spec:
  refreshInterval: 600s
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: postgresdb-secret # secret name to be created in k8s
    creationPolicy: Owner
  data:
  - secretKey: host # key in the k8s secret
    remoteRef:
      key: postgresdb-credentials # secret name used in the external secret store
      property: host # key name used in the external secret store
  - secretKey: maxIdleConn # key in the k8s secret
    remoteRef:
      key: postgresdb-credentials 
      property: maxIdleConn # key name used in the external secret store
  - secretKey: maxOpenConn # key in the k8s secret
    remoteRef:
      key: postgresdb-credentials 
      property: maxOpenConn # key name used in the external secret store
  - secretKey: name # key in the k8s secret
    remoteRef:
      key: postgresdb-credentials 
      property: name # key name used in the external secret store
  - secretKey: password # key in the k8s secret
    remoteRef:
      key: postgresdb-credentials 
      property: password # key name used in the external secret store
  - secretKey: port # key in the k8s secret
    remoteRef:
      key: postgresdb-credentials 
      property: port # key name used in the external secret store
  - secretKey: username # key in the k8s secret 
    remoteRef:
      key: postgresdb-credentials 
      property: username # key name used in the external secret store